export const consoles = [
    {
        id: '1',
        name: 'Atari',
        year: '1977',
        desc: 'Classically viewed as the original game console.',
        top: '200px',
        left: '50%',
    },
    {
        id: '2',
        name: 'NES (Famicon in Japan)',
        year: '1983',
        desc: 'Considered to be what put gaming consoles onto the market.',
        top: '200px',
        left: '50%',
    },
    {
        id: '3',
        name: 'Sega',
        year: '1983',
        desc: 'Nintendos competitor.Failed to compete on the first wave of consoles.',
        top: '200px',
        left: '50%',
    },
    {
        id: '4',
        name: 'Sony PlayStation',
        year: '1994',
        desc: 'The game changer. This console set a new standard for gaming. 3D models and environments were starting to become the new standard. It led its generation',
        top: '200px',
        left: '50%',
    },
    {
        id: '5',
        name: 'Nintendo 64',
        year: '1996',
        desc: 'This competed with the PS1 for the most part and was overall loved despite losing out in the end.',
        top: '200px',
        left: '50%',
    }}